### ISSUE TITLE
Issue with add & subtract functions

### ISSUE THREAD

**Issue by TheTeaCup** [TrueXPixels/quick.db#117]
#### Issue:
*All of my economy commands stopped working yesterday with the same error*
Error:
https://hastebin.com/osoxahecih.coffeescript
#### Steps To Reproduce:
Code: https://hastebin.com/rubaliwesi.js

#### Further Information:
- Operating System: linux x64
- Node.js Version: 8.11.3
- Quick.db Version: 6.3.2
- Any other details: I'm hosting my bot on glitch

**Comment by TheTeaCup** [comment]
its been almost an week can someone PLEASE HELP ME?
I really need Economy back online on my bot

**Comment by Etzyy** [comment]
Variable numbers is a string.

**Comment by TheTeaCup** [comment]
Ive got it working by adding an extra line 
but i forgot to close this issue
