### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by GarrettBlackmon** [TrueXPixels/quick.db#119]
I am using quick.db to store some very simple key/value pairs for a Discord bot. I noticed the documentation in readme.md and the website seem to be outdated sighting get() as the query function while in code it has been named fetch(). I could probably clean that up for you if I familiarize myself with the module enough.

I am also having issues since the fetch function seems to return a promise.

Regards,
-Garrett

**Comment by TrueXPixels** [comment]
Hello;

`.get()` is an alias of `.fetch()`. Therefore, both currently work.

Thank you!
