### ISSUE TITLE
db.startsWith() bug

### ISSUE THREAD

**Issue by JSmental** [TrueXPixels/quick.db#124]
# **Describe the bug**
When I fetch data using 
```javascript
db.fetch(`key_${message.guild.id}`)
```
I get data, however when I try to fetch data using 
```javascript
db.startsWith(`key_${message.guild.id}`)
```
**in the same file** I get an empty array

# **Example**

![image](https://user-images.githubusercontent.com/37380158/50379446-e4a26680-0641-11e9-8dd7-63847fbaa330.png)

**Comment by Tonerre** [comment]
db.startsWith('Leveling')

**Comment by codepupper** [comment]
I would  do it like in the Comment above. Though, when I tried it out locally, both worked.

![](https://yiff.design/i/ro7g.png)

**Comment by TrueXPixels** [comment]
This issue seems to be resolved. If not, feel free to re-open this issue.
We are looking into adding post-install scripts to ensure everyone has a reliable and easy experience using quick.db.

Thank you!
