### ISSUE TITLE
Cant install quick.db on Ubuntu

### ISSUE THREAD

**Issue by DubbyYT** [TrueXPixels/quick.db#125]
**Describe the bug**

Whenever I go to install quick.db on my ubuntu root server it shoots out this error:
`> integer@2.1.0 install /root/osrp_bot/node_modules/integer
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/osrp_bot/node_modules/integer
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok`

**To Reproduce**
1. Attempt to install quick.db with 'npm install quick.db' on an ubuntu server
2. See error

**Expected behavior**
Quick.db will install correctly and be ready for use with Nodejs and NPM

**Screenshots**
N/A (All evidence provided above)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian 9 64bit Minimal
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] V9

**Smartphone (please complete the following information):**
N/A

**Additional context**
I noticed that error is similiar to the error given on windows.
However, there is no written fix for this problem on Ubuntu

**Comment by chroventer** [comment]
Hey @DubbyYT,
If you're running Ubuntu, you'll need to install the build-essential package:
`$ sudo apt-get install build-essential`
Once you're done installing build-essential, install Quick.db again,
`$ npm i quick.db`

**Comment by codepupper** [comment]
@DubbyYT 

Did this work? If so, please close this Issue, thanks!

**Comment by TrueXPixels** [comment]
It looks like this issue has been resolved!

If not, feel free to re-open this issue.

**Comment by anburocky3** [comment]
I'm on Ubuntu 19.10 and i tried

> Hey @DubbyYT,
> If you're running Ubuntu, you'll need to install the build-essential package:
> `$ sudo apt-get install build-essential`
> Once you're done installing build-essential, install Quick.db again,
> `$ npm i quick.db`

I'm on Ubuntu 19.10 and i tried this technique, it didn't work.. Is it bug?

**Comment by herseyimburda** [comment]
its really bug gosh

**Comment by AshReks** [comment]
It didn't work fr me too!

**Comment by aspekts** [comment]
Works for me... Thank you!

Btw im on Ubuntu 21.04
