### ISSUE TITLE
Shard ? 

### ISSUE THREAD

**Issue by TutoRapide** [TrueXPixels/quick.db#126]
Hello 
quick.db supports sharding ?

**Comment by codepupper** [comment]
bump

**Comment by chroventer** [comment]
Hello @TutoRapide;
Quick.db does support Discord.js sharding, however, to a limited amount.

**Comment by TutoRapide** [comment]
Hello what is this amount

**Comment by chroventer** [comment]
Hey @TutoRapide,
We've currently tested that 25 shards worked perfectly!
However, we're still not sure about this estimation.
PS: Quick.db supports internal sharding.

**Comment by TutoRapide** [comment]
ok thank
