### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AuguxX** [TrueXPixels/quick.db#127]
I want to know if is there any examples, ive made a points bot but, when i do !padd @user1 23, works fine then i do !points @user1 response "23" but when i do !points @user2 response its equal than user1 that means that variable its equals to all users. (db.set ('user', {guild: message.mentions.users.first ().id, points: 0}) and db.add not working tho, it just sets a new value

**Comment by chroventer** [comment]
Hey @AuguxX, 
The ID of the key is "user";
And when you're fetching the points, you're fetching the "user" key, which should return the user ID, I think it is working just fine.

you should rather do this:
```js
const db = require('quick.db');
const userID = '1234567890';

db.set(`user_${userID}`);

// Replace "userID" with mentioned user ID.
const fetched = db.get(`user_${userID}`);
console.log(fetched);
```

**Comment by codepupper** [comment]
@AuguxX 

Did this work? If so, please close this Issue, thanks!

**Comment by TrueXPixels** [comment]
It looks like this issue has been resolved!

If it hasn't, feel free to re-open this issue.
