### ISSUE TITLE
Error: .add() data is not a number.

### ISSUE THREAD

**Issue by FrostyHyperX** [TrueXPixels/quick.db#135]
`
     const discord = require('discord.js');
     const db = require('quick.db');
     const utils = require('../global/utils1.js');

      module.exports.run = async (bot, message, args) => {   
  
    if (!message.member.hasPermission('ADMINISTRATOR')) {
        return message.reply('Nope').then(msg => {
          setTimeout(() =>{
          msg.delete()
          }, 2500)
    })
  }
   if (!args[0]) return message.reply('Please specify an amount to add.')
    if (isNaN(args[0])) return message.reply('That was not a valid number!')
    let moneytoadd = args[0];
    let user = message.mentions.users.first() || message.author
    message.channel.send('Successfully added ' + args[0] + ' to ' + user)
    db.add(`money_${user.id}`, moneytoadd)

}

module.exports.help = {
    name: 'moneyadd',
    aliases: []
};
`
That telling me that moneytoadd is not a numer but if i do console.log(moneytoadd) it shows me clearly a number

**Comment by chroventer** [comment]
Hey @FrostyHyperX,

Join quick.db official [Discord server](https://discord.gg/plexidev) to receive additional support.
