### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Roki100** [TrueXPixels/quick.db#141]
**1.** Any benchmarks of this db?
like qucik.db vs rethinkdb vs redis vs mysql or something?

**2.** Does this database limit me to any space? or its unlimited, and db will not do stuff like corruption, being slow etc?

**3.** Is this database fast?

**4.** Will it be fast on bot for example with 20k servers, 20 shards, and high load?

**Comment by chroventer** [comment]
1. There are no benchmark for Quick.db YET
2. It depends upon your storage since SQLite is a file-type database.
3. Yes, SQLite3 is much faster than MySQL database. It's because file database is always faster than unix socket.
4. I think Quick.db does not support shards.

**Comment by Roki100** [comment]
1. waiting till it will have
2. okay, nice
3. good
4. it does, check some other issue, but it doesnt matter, i mean there is nothing to do to support sharding xD, sharding doesnt force databases etc. to support it, it just works.

**Comment by chroventer** [comment]
> 4\. force

It will eventually come to halt after a certain number of shards, This issue has been reported by one of the Quick.'s contributor, SQLite does not generally support shards, that is.

**Comment by MathoCraft** [comment]
why is there no db.remove on quick.db?

**Comment by chroventer** [comment]
> why is there no db.remove on quick.db?

Hey there, @MathoCraft!

Unfortunately, you're mistaken. Quick.db does support removal of a key, however, it has a different name (`delete()`).

Cheers & Thanks!

**Comment by TehPigYT** [comment]
Is there a way to remove certain items from a database in quick.db? I know that we're able to delete databases but are we able somehow to do the first thing said? If yes, please contact me on Discord

Username & Tag: TehPig_YT#9063

**Comment by Androz2091** [comment]
What do you mean by "remove certain items"? You can delete/remove a key and its content, I don't see what more we could remove?

**Comment by TehPigYT** [comment]
Let's take an example here: Let's say that I have a crates system ok? After opening the crate, it should delete it, too. Although I don't want to erase all the crates stored in the user but just the certain one that the user opened.

**Comment by Androz2091** [comment]
You can store all the user's crates in an array:

```js
db.set("crates_"+message.author.id, [ "someInfoCrate1", "someInfoCrate2" ];
```
This will save an array of crates in the `crates_IDofTheUser` key.
To remove a crate and not all the  crates you can do it like this:
```js
let crates = db.fetch("crates_"+message.author.id);
// The user opens a crate so we need to remove the first one
db.set("crates_"+message.author.id, crates.slice(1, crates.length));
```
It will remove the first crate only from the db
Is it what you were asking?

**Comment by ZoroSC** [comment]
@Roki100 @chroventer I plan on possibly making a separate module which will hopefully support multi-connection sharding. however its not expected to scale that much due to it being made around sqlite3.

**Comment by TehPigYT** [comment]
@Androz2091 you mean like creating a seperate id for each crate?

**Comment by Androz2091** [comment]
I mean each user has a key for its crates like `crates_USERID`. Its crates are stored in an array like:
```js
console.log(db.fetch(`crates_029202009282`)); // Display the crates of the user with ID 029202009282
```
Returns
```js
[
    "2 credits",
    "1 bottle of xp",
    "40 money"
]
```
And when a user opens a crate, you remove it form the array.

**Comment by TehPigYT** [comment]
Ohhhh, so if I'm using the push function, the crates will be saved as arrays and doing the upper code shown, I can divide the crates by that way.

I have now understood what you're saying. Thanks for your help!

**Comment by TehPigYT** [comment]
@Androz2091 Also, one more question. Can I count the arrays somehow?

**Comment by Androz2091** [comment]
Count the total number of arrays that have a `crates_something` key?

**Comment by TehPigYT** [comment]
Exactly as you said it!

**Comment by Androz2091** [comment]
You can't easily do that. The only way to count it is to have a key created for this purpose, which you will increment when you create a new array. Like this.
```js
db.fetch(`number_of_crates`); // 0 for example
db.set(`crates_something`, []);
db.add(`number_of_crates`, 1);
db.fetch(`number_of_crates`); // 1
```
It's one of the Quick.DB's limits...

**Comment by Androz2091** [comment]
The length function will be useful if you have to count the number of a user's crates. But not if you have to count the number of users in the db

**Comment by TehPigYT** [comment]
I just need to count the crate count.

**Comment by TehPigYT** [comment]
And finally, how can I make the arrays appear as I want them to be?

Like using `args.join(" | ")`
Can I make the crates to be like `crates.join(" | ")` ?

**Comment by TehPigYT** [comment]
Thank you so much for all your help today! It has been really appreciated!
Have a good rest of your day! :)

**Comment by Androz2091** [comment]
No problem 😄 
Have a good day too

**Comment by chroventer** [comment]
@Androz2091, apparently not.

**Comment by TehPigYT** [comment]
One more question. As we said about the crates removal, how can I make it so that it removes a specific entry? Like using db.push(`something`, Name goes here) and I want to remove the third one of 5. Can I use the entry number of something like that? As you told me to use `crates.length`

**Comment by chroventer** [comment]
> One more question. As we said about the crates removal, how can I make it so that it removes a specific entry? Like using db.push(`something`, Name goes here) and I want to remove the third one of 5. Can I use the entry number of something like that? As you told me to use `crates.length`

```javascript
db.set('crates', ['crate1', 'crate2', 'crate3']);
const data = db.get('crates');
delete data[1];
db.set('crates', );
```

**Comment by TehPigYT** [comment]
Can you explain it a bit?

**Comment by TehPigYT** [comment]
@chroventer Also, db.get is not a function.

**Comment by chroventer** [comment]
> @chroventer Also, db.get is not a function.

db#get function is added in newer versions of Quick.db. It's just an alias of db#fetch.

**Comment by TehPigYT** [comment]
So, can I use db.fetch() too?

**Comment by TehPigYT** [comment]
@chroventer

**Comment by TrueXPixels** [comment]
Thank you for your interest in quick.db, you can discuss about it more in https://discord.gg/plexidev
