### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Roki100** [TrueXPixels/quick.db#142]
**Is your feature request related to a problem? Please describe.**
I like databases that has web panel (like rethink db) its cool

**Describe the solution you'd like**
Support of starting web panel/dashboard or something like that, that shows for example, reads/s, writes/s tables, tables that has issues/problems etc.

**Describe alternatives you've considered**
CLI panel

**Additional context**
Support for binding to localhost:port

**Comment by UniverseCodes** [comment]
@Roki100 hey, i'm not a dev of quick.db . But i might be able to do this. If you want to contact me, pm me on discord: Universe#7440

**Comment by ZoroSC** [comment]
We used to have something like this, however removed its support, However there is already software that already accomplish this. such as: https://dbeaver.io
