### ISSUE TITLE
Hard Spaces Not Working In the Sponsor Message

### ISSUE THREAD

**Issue by davidhaw** [TrueXPixels/quick.db#148]
**Describe the bug**
There are hard spaces (&nbsp) in the sponsor message that show &nbsp instead of a hard space and look as if the hard space wasn't coded right and didn't work. 

**To Reproduce**
1. Go to https://quickdb.js.org/
2. Scroll down to the footer of the page
3. See &nbsp in the sponsor message

**Expected behavior**
A hard base showing instead of the &nbsp 

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 77

**Comment by TrueXPixels** [comment]
Fixed
