### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by Uthsho** [TrueXPixels/quick.db#149]
I have a discord bot and i wanna make a command where i can remove premium from server
how do i do it?

**Comment by Androz2091** [comment]
We need more information to answer you. Like the way your database is structured

**Comment by Uthsho** [comment]
i add premium on guilds using db.set(`premium_${message.guild.id}`, msg)
how to remove premium from a server if i want to using a command?

**Comment by Androz2091** [comment]
Try with db.delete(`premium_${message.guild.id}`);

**Comment by Uthsho** [comment]
Thanks. It works now. :D
