### ISSUE TITLE
Getting errors on run.

### ISSUE THREAD

**Issue by gamingdiamond982** [TrueXPixels/quick.db#153]
**I get this error when I run my code**
I've used quick.db before and everything has gone fine I don't know what the issue is now
> C:\node_modules\quick.db\bin\handler.js:240
>  db.prepare(`CREATE TABLE IF NOT EXISTS ${options.table} (ID TEXT, json TEXT)`).run();
>     ^
> SqliteError: file is not a database

**Comment by Androz2091** [comment]
Can you paste your code please?

**Comment by gamingdiamond982** [comment]
sorry I don't comment much
`
//Startup stuff

console.log("loading...")
const Discord = require('discord.js');
const client = new Discord.Client();
const db = require('quick.db');
client.once('ready', () => {
	let allUsers = client.users.array();
	for(let i = 0; i < allUsers.length; i++){
		if(!(db.get(allUsers[i].id))){
		db.set(allUsers[i].id, {insurancePremium: null})
		
		}
		
	}		
	console.log('Ready!');

	
});

client.login('NjI4MzM3NTQ3NzYzNzc3NTc0.XZOSbg.SyhCynaHoOrTrJhGeJz6DnOhtUk');
console.log("almost there...")
var active = false
var questionsAsked = null
//Start of message parsing
client.on("message", message =>{
	if (message.author.id === "628337547763777574") return;
	const server = message.guild
	const iChannel = server.channels.find('name', 'insurance-calculator')
	if (message.channel.id === "637748327550681119"){
		if (message.content.startsWith("!ICalcPremium")){
			if (active === false){
				console.log(message.author.id + " is calculating his insurance premiums")
				active = true
				var calculatorID = message.author.id
				db.set(calculatorID, {insurancePremium: 0})

				
				message.member.addRole('649718621852925983')
				iChannel.send(`${message.member} Please respond correctly to all of the questions correctly.`)
				iChannel.send("If any questions are answered incorrectly then Baos reserves the right to refuse to pay any payouts you may be otherwise entitled to.")
				iChannel.send("question 1:")
				iChannel.send("How many times have you lost a lawsuit?")
				console.log("{-_-} Debug: Calc Channel Roadmark 0 reached")
				console.log(calculatorID)
				questionsAsked = 1
				console.log("{-_-} Debug: Asked Questions: " + questionsAsked)
  			};
		};
	};

	if (message.channel.id === "649718622108778525")	{
		var ans = message.content
		console.log("{-_-} Debug: logged Answer: " + ans)
		console.log("{-_-} Debug: Calc Channel Roadmark 1 reached")
		console.log("{-_-} Debug: Asked Questions: " + questionsAsked)
		if (questionsAsked == 1){
			console.log("{-_-} Debug: Calc Channel Roadmark 2 reached")
			ans = parseInt(ans)
			console.log("{-_-} Debug: ans is now equal to: " + ans)
			var currentPrem = db.get(`${calculatorID}.insurancePremium`)
			console.log("{-_-} Debug: currentPrem is now equal to: " + currentPrem)
			var insuranceMod = ans * 15
			console.log("{-_-} Debug: insuranceMod is now equal to: " + insuranceMod)
			var newPrem = currentPrem - insuranceMod
			console.log("{-_-} Debug: newPrem is now equal to: " + newPrem)
			db.set(`${calculatorID}`, {insurancePremium: newPrem, lostLawsuits: ans})
			iChannel.send("Answer has been noted.")
			iChannel.send("Question 2:")
			iChannel.send("How many times has somebody attempted but failed to sue you?")
			questionsAsked = 2
			}else if (questionsAsked == 2){
			console.log("{-_-} Debug: Calc Channel Roadmark 3 reached")
			ans = parseInt(ans)
			console.log("{-_-} Debug: ans is now equal to: " + ans)
			var currentPrem = db.get(`${calculatorID}.insurancePremium`)
			console.log("{-_-} Debug: currentPrem is now equal to: " + currentPrem)
			var insuranceMod = ans * 5
			console.log("{-_-} Debug: insuranceMod is now equal to: " + insuranceMod)
			var newPrem = currentPrem - insuranceMod
			console.log("{-_-} Debug: newPrem is now equal to: " + newPrem)
			db.set(`${calculatorID}`, {insurancePremium: newPrem, WonLawsuits: ans})
			iChannel.send("Answer has been noted.")
			iChannel.send("Question 3: ")
			iChannel.send("")
			questionsAsked = 3

		};
	};




	//start of admin commands
	if (!message.guild) return;

	

	//end of admin commands

});
//end of message Parsing



`

**Comment by Androz2091** [comment]
Ok, I will look into it. Warning, you have sent your token.
![Capture d’écran 2019-11-30 à 11 22 24](https://user-images.githubusercontent.com/42497995/69899248-ca016300-1363-11ea-9aa4-28e049de2a7b.png)

**Comment by gamingdiamond982** [comment]
oops

**Comment by gamingdiamond982** [comment]
it turns out I corrupted the sqlite file so alls good.
