### ISSUE TITLE
rejection '-'

### ISSUE THREAD

**Issue by lelbr** [TrueXPixels/quick.db#156]
When i try to buy something on my bot, this happens.
(node:17544) DeprecationWarning: ClientUser#setGame: use ClientUser#setActivity instead
(node:17544) UnhandledPromiseRejectionWarning: Error: Target is not a number.
at Object.module.exports [as subtract] (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\quick.db\lib\subtract.js:29:36)
at arbitrate (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\quick.db\bin\handler.js:260:25)
at Object.subtract (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\quick.db\bin\handler.js:82:12)
at Object.module.exports.run (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\commands\buy.js:30:12)
at Client. (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\index.js:40:17)
at Client.emit (events.js:321:20)
at MessageCreateHandler.handle (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
at WebSocketPacketManager.handle (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
at WebSocketConnection.onPacket (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
at WebSocketConnection.onMessage (C:\Users\leona\OneDrive\Área de Trabalho\Piratas do Arybe\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
(node:17544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.<

**Comment by Androz2091** [comment]
@lelbr, can you send your code? (the lines you use `subtract`)

**Comment by lelbr** [comment]
> @lelbr, can you send your code? (the lines you use `subtract`)

const Discord = require('discord.js')
const db = require('quick.db')

module.exports.run = async (bot, message, args) => {
    if(!message.content.startsWith('!'))return;  

    let user = message.author;

    let author = db.fetch(`money_${message.guild.id}_${user.id}`)

    let canhaorole = message.guild.roles.get("671464285569810464");

    let espadarole = message.guild.roles.get("671801998458224640");

    let Embed = new Discord.RichEmbed()

    .setColor("#FFFFFF")
    .setDescription(`Você precisa de 7000 para comprar um canhão!`);

    if (args[0] == 'canhão') {
        if (author < 7000) return message.channel.send(Embed)
        
        db.fetch(`canhao_${message.guild.id}_${user.id}`);
        db.set(`canhao_${message.guild.id}_${user.id}`, true)

        let Embed2 = new Discord.RichEmbed()
        .setColor("#FFFFFF")
        .setDescription(`<:Check:618736570337591296> Comprou canhão por 7000!!`);

        db.subtract(`money_${message.guild.id}_${user.id}`, 7000)
        message.member.addRole(canhaorole);
        message.channel.send(Embed2)
        
    } else if(args[0] == 'proteção') {
        let Embed2 = new Discord.RichEmbed()
        .setColor("#FFFFFF")
        .setDescription(`YARGH! Precisas de 1.000 para comprar!`);

        if (author < 1000) return message.channel.send(Embed2)
       
        db.fetch(`life_${message.guild.id}_${user.id}`)
        db.add(`life_${message.guild.id}_${user.id}`, 500)

        let Embed3 = new Discord.RichEmbed()
        .setColor("#FFFFFF")
        .setDescription(`Compraste proteção!`);

        db.subtract(`money_${message.guild.id}_${user.id}`, 1000)
        message.channel.send(Embed3)

    } else if (args[0] == 'sabre') {
        let Embed8 = new Discord.RichEmbed()

        .setColor("#FFFFFF")
        .setDescription(`Você precisa de 700 para comprar um sabre!`);

        if (author < 700) return message.channel.send(Embed8)
        
        db.fetch(`espada_${message.guild.id}_${user.id}`);
        db.set(`espada_${message.guild.id}_${user.id}`, true)

        let Embed10 = new Discord.RichEmbed()
        .setColor("#FFFFFF")
        .setDescription(`Compraste el espadon!!`);

        db.subtract(`money_${message.guild.id}_${user.id}`, 700)
        message.member.addRole(espadarole);
        message.channel.send(Embed10)
    } else {
        let embed3 = new Discord.RichEmbed()
        .setColor("#FFFFFF")
        .setDescription('<:Cross:618736602901905418> Enter an item to buy')
        message.channel.send(embed3)
    }

}
  
  module.exports.help = {
    name:"buy",
    aliases: [""]
  }

**Comment by Androz2091** [comment]
Hmm.. In another place in your code you should defined this key with a non-number value I think, like a string.
Search in your code for any files that modify the `money_${message.guild.id}_${user.id}` key.

**Comment by TrueXPixels** [comment]
Unable to reproduce
