### ISSUE TITLE
Table name as a db option

### ISSUE THREAD

**Issue by vekat** [TrueXPixels/quick.db#157]
**Is your feature request related to a problem? Please describe.**
I would like to insert data on a specific table without needing to create a table object.

**Describe the solution you'd like**
We know that `db.table()` is a simple wrapper that fixes a `tableName` to `arbitrate()`. I would like to send `tableName` as an option from any db function. For example:
```javascript
db.set('value', 'data in json table')
db.get('value') // 'data in json table'

let table = new db.table('test')
table.set('value', 'data in test table')
table.get('value') // 'data in test table'

// I want this to be possible
db.get('value', { tableName: 'test' }) // 'data in test table'

// but since it's not implemented, this is what happens
db.get('value', { tableName: 'test' }) // 'data in json table'
```

**Describe alternatives you've considered**
I've considered forking and adding this feature myself.

**Additional context**
None.

**Comment by ZoroSC** [comment]
I'll go ahead and add this real quick 😄

**Comment by vekat** [comment]
Oh, sorry @ZoroSC I wasn't expecting a quick answer.

**Comment by ZoroSC** [comment]
@vekat All good 👍 I'm glad you did it yourself as I'm a little per-occupied right now.

Good suggestion btw

**Comment by ZoroSC** [comment]
Quick note as well. You have to install this version of quick.db by doing "npm i truexpixels/quick.db"
